config/routes.rb
Rails.application.routes.draw do
  namespace :home do
    get 'other_data/crime_labour'
    get 'other_data/crime_covid'
  end
  namespace :home do
    get 'covid_data/cases'
    get 'covid_data/deaths'
    get 'covid_data/hospitalizations'
  end
  namespace :home do
    get 'labour_data/unemployment'
    get 'labour_data/labourForce'
    get 'labour_data/employment'
  end
  #get 'home/homepage'
  root 'home#homepage'

  get 'home/labour_data'

  get 'home/crime_data'
  
  get 'home/covid_data'
  
  get 'home/other_data'
  get 'home/covid_data/deaths'
  #get 'home/otherData/crimeLabour'
  #get 'home/otherData/crimeCovid'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home/covid_data_controller.rb
class Home::CovidDataController < ApplicationController
  def cases
  end

  def deaths
  end

  def hospitalizations
  end
end

app/controllers/home/labour_data_controller.rb
class Home::LabourDataController < ApplicationController
  def unemployment
  end

  def labourForce
  end

  def employment
  end
end

app/controllers/home/other_data_controller.rb
class Home::OtherDataController < ApplicationController
  def crime_labour
  end

  def crime_covid
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  end

  def labour_data
  end

  def crime_data
  end

  def covid_data
  end

  def other_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home/covid_data_helper.rb
module Home::CovidDataHelper
end

app/helpers/home/labour_data_helper.rb
module Home::LabourDataHelper
end

app/helpers/home/other_data_helper.rb
module Home::OtherDataHelper
end

app/helpers/home_helper.rb
require 'ruby-oci8'
module HomeHelper
	def connect
		#username and password needs to be edited to yours
		oci=OCI8.new('hesun','092700Jimmy','oracle.cise.ufl.edu:1521/orcl')
		oci.exec('SELECT L.LABOR_FORCE, D.D_YEAR, D.D_MONTH
				FROM "G.AGRAWAL"."LABOR_DATA" L, "G.AGRAWAL"."DATEVALUES" D
				WHERE L.D_ID=D.D_ID') do |record|
				concat record.join("\b\n")
			end
		oci.logoff
	end
end

app/views/home/_header.html.erb
<ul class="nav justify-content-center align-items-center">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Labour Data', home_labour_data_path, class:"btn btn-sm btn-outline-secondary me-3"%>
            <%= link_to 'COVID Data', home_covid_data_path, class:"btn btn-sm btn-outline-secondary me-3"%>
            <%= link_to 'Home', root_path, class:"btn btn-outline-success me-3"%>
            <%= link_to 'Crime Data', home_crime_data_path, class:"btn btn-sm btn-outline-secondary me-3"%>
            <%= link_to 'Other Data', home_other_data_path, class:"btn btn-sm btn-outline-secondary me-3"%>
        </li>
      </ul>
    </div>
  </div>
</nav>
</ul>

app/views/home/covidData.html.erb
<h1>COVID Data </h1>

app/views/home/covid_data.html.erb
<h1>COVID Data </h1>

<body>
<form method="get" action="covid_data/cases">
	<button>cases</button>
</form>
<form method="get" action="covid_data/deaths">
	<button>deaths</button>
</form>
<form method="get" action="covid_data/hospitalizations">
	<button>hospitalizations</button>
</form>
</body>
</body>a

app/views/home/covid_data/cases.html.erb
<h1>Home::CovidData#cases</h1>
<p>Find me in app/views/home/covid_data/cases.html.erb</p>

app/views/home/covid_data/deaths.html.erb
<h1>Home::CovidData#deaths</h1>
<p>Find me in app/views/home/covid_data/deaths.html.erb</p>

app/views/home/covid_data/hospitalizations.html.erb
<h1>Home::CovidData#hospitalizations</h1>
<p>Find me in app/views/home/covid_data/hospitalizations.html.erb</p>

app/views/home/crimeData.html.erb
<h1>Crime Data </h1>

app/views/home/crime_data.html.erb
<h1>Crime Data </h1>

app/views/home/homepage.html.erb
<h1>HomePage</h1>
<p>4 buttons for Labour data, COVID Data, Crime Data, and Other Complex Queries</p>

app/views/home/labourData.html.erb
<h1>Labour Data </h1>

app/views/home/labour_data.html.erb
<h1>Labour Data </h1>

<body>
<form method="get" action="labour_data/employment">
	<button>employment</button>
</form>
<form method="get" action="labour_data/labourForce">
	<button>labourForce</button>
</form>
<form method="get" action="labour_data/unemployment">
	<button>unemployment</button>
</form>
</body>
</body>

app/views/home/labour_data/employment.html.erb
<h1>Home::LabourData#employment</h1>
<p>Find me in app/views/home/labour_data/employment.html.erb</p>
<%= connect %>

app/views/home/labour_data/labourForce.html.erb
<h1>LabourForce</h1>
<p>Find me in app/views/home/labour_data/labourForce.html.erb</p>
<%= bar_chart(a:1,b:10,c:9) %>

app/views/home/labour_data/unemployment.html.erb
<h1>Home::LabourData#unemployment</h1>
<p>Find me in app/views/home/labour_data/unemployment.html.erb</p>

app/views/home/otherData.html.erb
<h1>Other Data </h1>

app/views/home/other_data.html.erb
<h1>Other Data </h1>

the following should be the sql query result
<%= connect%>

app/views/home/other_data/crime_covid.html.erb
<h1>Home::OtherData#crime_covid</h1>
<p>Find me in app/views/home/other_data/crime_covid.html.erb</p>

app/views/home/other_data/crime_labour.html.erb
<h1>Home::OtherData#crime_labour</h1>
<p>Find me in app/views/home/other_data/crime_labour.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>UIDesign</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/header' %>
  <div class="d-flex justify-content-center align-items-center" style="height:100px;">
  <div style="height: 100px">
    <%= yield %>
  </div>
</div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>